- name: Create HAProxy configuration directory
  file:
    path: /etc/haproxy
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy HAProxy configuration from template
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Deploy HAProxy container
  docker_container:
    name: "{{ ENV_HAPROXY_CONTAINER_NAME }}"
    image: "{{ ENV_HAPROXY_IMAGE }}"
    restart_policy: always
    state: started
    ports:
      - "80:80"
      - "{{ ENV_HAPROXY_STATS_PORT }}:{{ ENV_HAPROXY_STATS_PORT }}"
    volumes:
      - /etc/haproxy:/usr/local/etc/haproxy:ro

- name: Ensure HAProxy container is running
  docker_container:
    name: "{{ ENV_HAPROXY_CONTAINER_NAME }}"
    state: started
  