- name: Crear volumen para datos persistentes de WordPress
  docker_volume:
    name: wordpress_data

- name: Deploy WordPress container
  docker_container:
    name: "{{ ENV_WORDPRESS_CONTAINER_NAME }}"
    image: "{{ ENV_WORDPRESS_IMAGE }}"
    state: started
    restart_policy: always
    ports:
      - "{{ ENV_WORDPRESS_PORT }}:80"
    env:
      WORDPRESS_DB_HOST: "{{ ENV_MYSQL_HOST }}:{{ ENV_MYSQL_PORT }}"
      WORDPRESS_DB_USER: "{{ ENV_MYSQL_USER }}"
      WORDPRESS_DB_PASSWORD: "{{ ENV_MYSQL_PASSWORD }}"
      WORDPRESS_DB_NAME: "{{ ENV_MYSQL_DATABASE }}"
    volumes:
      - wordpress_data:/var/www/html

- name: Asegurarse de que el contenedor de WordPress esté en ejecución
  docker_container:
    name: "{{ ENV_WORDPRESS_CONTAINER_NAME }}"
    state: started
