# filepath: /home/ivan/Playbook/roles/wordpress/tasks/main.yml
- name: Run WordPress container
  docker_container:
    name: "{{ wordpress_container_name }}"
    image: "{{ wordpress_image }}"
    env:
      WORDPRESS_DB_HOST: "{{ wordpress_db_host }}"
      WORDPRESS_DB_USER: "{{ wordpress_db_user }}"
      WORDPRESS_DB_PASSWORD: "{{ wordpress_db_password }}"
      WORDPRESS_DB_NAME: "{{ wordpress_db_name }}"
    ports:
      - "{{ wordpress_port_mapping }}"
    networks:
      - name: "{{ wordpress_network }}"
    state: "{{ wordpress_state }}"