- name: Crear volumen para MySQL
  docker_volume:
    name: mysql_data
    state: present

- name: Crear y ejecutar el contenedor de MySQL
  docker_container:
    name: "{{ ENV_MYSQL_CONTAINER_NAME }}"
    image: "{{ ENV_MYSQL_IMAGE }}"
    state: started
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "{{ ENV_MYSQL_ROOT_PASSWORD }}"
      MYSQL_DATABASE: "{{ ENV_MYSQL_DATABASE }}"
      MYSQL_USER: "{{ ENV_MYSQL_USER }}"
      MYSQL_PASSWORD: "{{ ENV_MYSQL_PASSWORD }}"
    published_ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

- name: Ajustar permisos del volumen de MySQL
  file:
    path: /var/lib/docker/volumes/mysql_data/_data
    state: directory
    owner: "999"
    group: "999"
    mode: "0755"

- name: Verificar que el contenedor de MySQL esté en ejecución
  docker_container_info:
    name: "{{ ENV_MYSQL_CONTAINER_NAME }}"
  register: mysql_info

- name: Mostrar información del contenedor de MySQL
  debug:
    msg: "Estado: {{ mysql_info.container.State.Status }}"
