- name: Get remote user
  set_fact:
    remote_user: "{{ ansible_user_id }}"

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install dependencies for HTTPS repositories
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - net-tools
    state: present

- name: Add Docker's official GPG key
  apt_key:
    url: "{{ ENV_DOCKER_GPG_KEY_URL }}"
    state: present

- name: Add Docker's official repository
  apt_repository:
    repo: "{{ ENV_DOCKER_REPO_URL }}"
    state: present
    filename: docker

- name: Update APT cache again
  apt:
    update_cache: yes

- name: Install Docker CE and dependencies
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Ensure Docker is running and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add remote user to Docker group
  user:
    name: "{{ remote_user }}"
    groups: docker
    append: yes

- name: Verify Docker installation
  command: docker --version
  register: docker_version_output
  failed_when: docker_version_output.rc != 0

- name: Show Docker version
  debug:
    var: docker_version_output.stdout

- name: Run Hello-World test container
  command: docker run hello-world
  register: hello_world_output
  failed_when: hello_world_output.rc != 0

- name: Show Hello-World output
  debug:
    var: hello_world_output.stdout