# Path: roles/common/tasks/main.yml
# DOCKER
ENV_DOCKER_GPG_KEY_URL: "{{ lookup('env','ENV_DOCKER_GPG_KEY_URL') }}"
ENV_DOCKER_REPO_URL: "{{ lookup('env','ENV_DOCKER_REPO_URL') }}"

# WORDPRESS
ENV_WORDPRESS_CONTAINER_NAME: "{{ lookup('env','ENV_WORDPRESS_CONTAINER_NAME') }}"
ENV_WORDPRESS_IMAGE: "{{ lookup('env','ENV_WORDPRESS_IMAGE') }}"
ENV_WORDPRESS_PORT: "{{ lookup('env','ENV_WORDPRESS_PORT') }}"

# MySQL
ENV_MYSQL_CONTAINER_NAME: "{{ lookup('env','ENV_MYSQL_CONTAINER_NAME') }}"
ENV_MYSQL_IMAGE: "{{ lookup('env','ENV_MYSQL_IMAGE') }}"
ENV_MYSQL_ROOT_PASSWORD: "{{ lookup('env','ENV_MYSQL_ROOT_PASSWORD') }}"
ENV_MYSQL_DATABASE: "{{ lookup('env','ENV_MYSQL_DATABASE') }}"
ENV_MYSQL_USER: "{{ lookup('env','ENV_MYSQL_USER') }}"
ENV_MYSQL_PASSWORD: "{{ lookup('env','ENV_MYSQL_PASSWORD') }}"
ENV_MYSQL_HOST: "{{ lookup('env','ENV_MYSQL_HOST') }}"
ENV_MYSQL_PORT: "{{ lookup('env','ENV_MYSQL_PORT') }}"

# HAPROXY
